version: '2'

services:
  alpine-nodemon:
    build:
      context: .
    ports:
      - 8080:8080
    image: alpine-nodemon:latest
    volumes:
      - ./src:/service/src
    command: npm run dev
    environment:
      - HTTP_PROXY=http://dependencies:8500
      - NODE_ENV=
    links:
      - dependencies
  dependencies:
    build:
      context: ./dependencies
    image: dependencies:latest
    ports:
      - 8888:8888
